'use client'

import { useAppLanguage } from '@/utils/use-app-language'

const copy = {
  zh: {
    systemManagement: '系统管理',
    apiKeys: 'API 密钥',
    channels: '渠道',
    serviceHours: '服务时间',
    helpCenter: '帮助中心',
    nav: '账号管理',
    title: '账号管理',
    subtitle: '管理租户账号、角色与资源访问范围',
    searchPlaceholder: '搜索用户名或邮箱',
    allRoles: '全部角色',
    admin: '管理员',
    qualityInspector: '质检员',
    clearFilters: '清除筛选',
    newAccount: '新建账号',
    username: '用户名',
    email: '邮箱',
    role: '角色',
    agentAccess: 'Agent 权限',
    knowledgeBaseAccess: '知识库权限',
    updatedAt: '更新时间',
    actions: '操作',
    noMatches: '未找到匹配的账号，请调整筛选条件',
    noAccounts: '暂无账号',
    currentAccount: '当前账号',
    all: '全部',
    notGranted: '未授权',
    granted: (count: number) => `已授权 ${count} 个`,
    total: (count: number) => `共 ${count} 条`,
    perPage: '每页',
    perPageItems: (count: number) => `${count} 条`,
    edit: '编辑',
    editAccount: '编辑账号',
    delete: '删除',
    deleteAccount: '删除账号',
    cannotDeleteCurrent: '不能删除当前登录账号',
    lastAdmin: '租户至少需要保留一个管理员',
    accountDeleted: '账号已删除',
    retry: '重新加载',
    listLoadFailed: '账号列表加载失败',
    deleteBody: '确定删除以下账号？删除后该账号将无法登录，且此操作不可撤销。',
    cancel: '取消',
    confirmDelete: '确定删除',
    formLoadFailed: '账号信息加载失败，请重试。',
    accountNotFound: '账号不存在',
    editTitle: (username: string) => `编辑：${username}`,
    save: '保存',
    basicInfo: '基本信息',
    usernamePlaceholder: '请输入用户名',
    emailPlaceholder: '请输入邮箱',
    currentCannotDowngrade: '当前登录账号不能降级',
    initialPassword: '初始密码',
    newPassword: '新密码（选填）',
    initialPasswordPlaceholder: '请输入初始密码',
    newPasswordPlaceholder: '留空则不修改',
    hidePassword: '隐藏密码',
    showPassword: '显示密码',
    generate: '随机生成',
    copyPassword: '复制密码',
    passwordCopied: '密码已复制，请妥善保管',
    passwordHint: '请在保存前复制并安全发送给用户，保存后将无法再次查看此密码。',
    resourceAccess: '资源权限',
    allAgents: '全部 Agent',
    allKnowledgeBases: '全部知识库',
    leaveTitle: '离开此页？',
    stay: '留在页面',
    leave: '离开',
    leaveBody: '有未保存的修改，离开后修改将丢失。',
    accountSaved: '账号信息已保存',
    accountCreated: '账号创建成功',
    duplicateUsername: '该用户名已存在',
    duplicateEmail: '该邮箱已被使用',
    selected: (count: number) => `已选择 ${count} 个`,
    select: '请选择',
    remove: (name: string) => `移除 ${name}`,
    search: '搜索',
    noResults: '无匹配结果',
    inactive: '已停用',
    adminFutureAccess: (label: string) => `${label}，并自动包含未来新增资源。`,
    emptyAccessAllowed: '允许不选择任何资源。',
    validation: {
      usernameRequired: '请输入用户名',
      usernameInvalid: '用户名为 4–32 位，仅支持字母、数字、点、下划线和短横线',
      emailRequired: '请输入邮箱',
      emailInvalid: '请输入有效的邮箱地址',
      passwordInvalid: '密码为 8–32 位，需包含大小写字母和数字',
    },
  },
  en: {
    systemManagement: 'System',
    apiKeys: 'API keys',
    channels: 'Channels',
    serviceHours: 'Service hours',
    helpCenter: 'Help center',
    nav: 'Accounts',
    title: 'Accounts',
    subtitle: 'Manage tenant accounts, roles, and resource access',
    searchPlaceholder: 'Search username or email',
    allRoles: 'All roles',
    admin: 'Administrator',
    qualityInspector: 'Quality inspector',
    clearFilters: 'Clear filters',
    newAccount: 'New account',
    username: 'Username',
    email: 'Email',
    role: 'Role',
    agentAccess: 'Agent access',
    knowledgeBaseAccess: 'Knowledge base access',
    updatedAt: 'Updated at',
    actions: 'Actions',
    noMatches: 'No matching accounts. Adjust your filters.',
    noAccounts: 'No accounts yet',
    currentAccount: 'Current account',
    all: 'All',
    notGranted: 'Not granted',
    granted: (count: number) => `${count} granted`,
    total: (count: number) => `${count} total`,
    perPage: 'Per page',
    perPageItems: (count: number) => `${count}`,
    edit: 'Edit',
    editAccount: 'Edit account',
    delete: 'Delete',
    deleteAccount: 'Delete account',
    cannotDeleteCurrent: 'You cannot delete the account you are signed in with',
    lastAdmin: 'At least one administrator must remain',
    accountDeleted: 'Account deleted',
    retry: 'Retry',
    listLoadFailed: 'Failed to load accounts',
    deleteBody: 'Delete this account? The account will no longer be able to sign in. This action cannot be undone.',
    cancel: 'Cancel',
    confirmDelete: 'Delete',
    formLoadFailed: 'Failed to load account information. Please try again.',
    accountNotFound: 'Account not found',
    editTitle: (username: string) => `Edit: ${username}`,
    save: 'Save',
    basicInfo: 'Basic information',
    usernamePlaceholder: 'Enter a username',
    emailPlaceholder: 'Enter an email',
    currentCannotDowngrade: 'You cannot downgrade the account you are signed in with',
    initialPassword: 'Initial password',
    newPassword: 'New password (optional)',
    initialPasswordPlaceholder: 'Enter an initial password',
    newPasswordPlaceholder: 'Leave blank to keep the current password',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    generate: 'Generate',
    copyPassword: 'Copy password',
    passwordCopied: 'Password copied. Store it securely.',
    passwordHint: 'Copy and securely share this password before saving. It cannot be viewed again afterward.',
    resourceAccess: 'Resource access',
    allAgents: 'All Agents',
    allKnowledgeBases: 'All knowledge bases',
    leaveTitle: 'Leave this page?',
    stay: 'Stay',
    leave: 'Leave',
    leaveBody: 'You have unsaved changes. They will be lost if you leave.',
    accountSaved: 'Account saved',
    accountCreated: 'Account created',
    duplicateUsername: 'This username already exists',
    duplicateEmail: 'This email is already in use',
    selected: (count: number) => `${count} selected`,
    select: 'Select',
    remove: (name: string) => `Remove ${name}`,
    search: 'Search',
    noResults: 'No matching results',
    inactive: 'Inactive',
    adminFutureAccess: (label: string) => `${label}, including resources added in the future.`,
    emptyAccessAllowed: 'No resource selection is required.',
    validation: {
      usernameRequired: 'Please enter a username',
      usernameInvalid: 'Username must be 4–32 characters using letters, numbers, dots, underscores, or hyphens',
      emailRequired: 'Please enter an email',
      emailInvalid: 'Enter a valid email address',
      passwordInvalid: 'Password must be 8–32 characters and include uppercase, lowercase, and a number',
    },
  },
} as const

export type AccountCopy = (typeof copy)['zh'] | (typeof copy)['en']

export function useAccountCopy(): AccountCopy {
  return copy[useAppLanguage()]
}
