"""initial schema

Revision ID: aa0ffb9fef05
Revises: 
Create Date: 2026-05-07 23:53:02.159717
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy  # noqa: F401  (referenced by autogen as pgvector.sqlalchemy.vector.VECTOR)

revision: str = 'aa0ffb9fef05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector extension is required by the slices.embedding column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('engine_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_agents_tenant_name')
    )
    op.create_index('ix_agents_tenant_id', 'agents', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_value', sa.String(length=128), nullable=False),
    sa.Column('masked_key', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.String(length=255), server_default='chat', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_value')
    )
    op.create_index('ix_api_keys_tenant_id', 'api_keys', ['tenant_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('access_mode', sa.String(length=16), nullable=False),
    sa.Column('secret_key', sa.String(length=64), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_key'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_channels_tenant_name'),
    # Use the same constraint name the old chain produced (uq_channels_token).
    sa.UniqueConstraint('token', name='uq_channels_token')
    )
    op.create_index('ix_channels_tenant_id', 'channels', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('doc_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('toc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slice_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'file_path', name='uq_documents_kb_filepath')
    )
    op.create_index('ix_documents_kb_id', 'documents', ['knowledge_base_id'], unique=False)
    op.create_index('ix_documents_tenant_id', 'documents', ['tenant_id'], unique=False)
    op.create_table('help_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('public_slug', sa.String(length=48), nullable=True),
    sa.Column('site_name', sa.String(length=64), nullable=True),
    sa.Column('publisher_logo_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_help_centers_tenant_id', 'help_centers', ['tenant_id'], unique=False)
    op.create_index('uq_help_centers_public_slug', 'help_centers', ['public_slug'], unique=True, postgresql_where=sa.text('public_slug IS NOT NULL'))
    op.create_table('kb_permission_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('user_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scope_operator', sa.String(length=32), nullable=False),
    sa.Column('scope_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_perm_rules_tenant_kb', 'kb_permission_rules', ['tenant_id', 'knowledge_base_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('git_url', sa.String(length=512), nullable=False),
    sa.Column('git_branch', sa.String(length=128), nullable=False),
    sa.Column('auth_type', sa.String(length=16), nullable=False),
    sa.Column('auth_token', sa.String(length=512), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('schema_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_knowledge_bases_tenant_name')
    )
    op.create_index('ix_knowledge_bases_tenant_id', 'knowledge_bases', ['tenant_id'], unique=False)
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reset_codes_expires', 'password_reset_codes', ['expires_at'], unique=False)
    op.create_index('ix_reset_codes_lookup', 'password_reset_codes', ['tenant_id', 'username', 'code'], unique=False)
    op.create_table('slices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_for_search', sa.Text(), nullable=True),
    sa.Column('toc_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('toc_ancestors', sa.Text(), nullable=True),
    sa.Column('slice_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('doc_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('markdown_url', sa.String(length=1024), nullable=True),
    sa.Column('slice_order', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slices_document_id', 'slices', ['document_id'], unique=False)
    op.create_index('ix_slices_kb_id', 'slices', ['knowledge_base_id'], unique=False)
    op.create_index('ix_slices_tenant_id', 'slices', ['tenant_id'], unique=False)
    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_super_admins_status', 'super_admins', ['status'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_logs_kb_id', 'sync_logs', ['knowledge_base_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=256), nullable=True),
    # `server_default='active'` patched in to match the old chain's behaviour.
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('admin_username', sa.String(length=64), nullable=False),
    sa.Column('admin_password_hash', sa.String(length=256), nullable=False),
    sa.Column('admin_email', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    # Patch (vs autogen): match old chain's `DEFAULT 'active'` for fresh installs.
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index('ix_tenants_status', 'tenants', ['status'], unique=False)
    op.create_table('agent_tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('tool_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('parameters_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'name', name='uq_agent_tools_agent_name')
    )
    op.create_index('ix_agent_tools_agent_id', 'agent_tools', ['agent_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('round_count', sa.Integer(), nullable=False),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('external_id', name='uq_conversations_external_id')
    )
    op.create_index('ix_conversations_status', 'conversations', ['status'], unique=False)
    op.create_index('ix_conversations_tenant_agent', 'conversations', ['tenant_id', 'agent_id'], unique=False)
    op.create_index('ix_conversations_tenant_started', 'conversations', ['tenant_id', 'started_at'], unique=False)
    op.create_table('help_center_tabs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('help_center_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('tab_slug', sa.String(length=48), nullable=True),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('fixed_filters', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['help_center_id'], ['help_centers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_help_center_tabs_help_center_id', 'help_center_tabs', ['help_center_id', 'sort_order', 'id'], unique=False)
    op.create_index('uq_help_center_tabs_help_center_slug', 'help_center_tabs', ['help_center_id', 'tab_slug'], unique=True, postgresql_where=sa.text('tab_slug IS NOT NULL'))
    op.create_table('conversation_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('thinking_enabled', sa.Boolean(), nullable=True),
    sa.Column('thinking_content', sa.Text(), nullable=True),
    sa.Column('request_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finish_reason', sa.String(length=32), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('tool_type', sa.String(length=32), nullable=True),
    sa.Column('tool_call_id', sa.String(length=128), nullable=True),
    sa.Column('tool_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_response', sa.Text(), nullable=True),
    sa.Column('brief', sa.String(length=512), nullable=True),
    sa.Column('parent_step_id', sa.Integer(), nullable=True),
    sa.Column('client_message_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_step_id'], ['conversation_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_steps_client_msg', 'conversation_steps', ['client_message_id'], unique=False, postgresql_where=sa.text('client_message_id IS NOT NULL'))
    op.create_index('ix_steps_conv_order', 'conversation_steps', ['conversation_id', 'step_order'], unique=False)
    op.create_index('ix_steps_conv_round', 'conversation_steps', ['conversation_id', 'round_number'], unique=False)
    op.create_index('ix_steps_parent', 'conversation_steps', ['parent_step_id'], unique=False)
    op.create_index('ix_steps_type', 'conversation_steps', ['step_type'], unique=False)
    op.create_index('ux_steps_conv_client_msg', 'conversation_steps', ['conversation_id', 'client_message_id'], unique=True, postgresql_where=sa.text("client_message_id IS NOT NULL AND step_type = 'user_message'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_steps_conv_client_msg', table_name='conversation_steps', postgresql_where=sa.text("client_message_id IS NOT NULL AND step_type = 'user_message'"))
    op.drop_index('ix_steps_type', table_name='conversation_steps')
    op.drop_index('ix_steps_parent', table_name='conversation_steps')
    op.drop_index('ix_steps_conv_round', table_name='conversation_steps')
    op.drop_index('ix_steps_conv_order', table_name='conversation_steps')
    op.drop_index('ix_steps_client_msg', table_name='conversation_steps', postgresql_where=sa.text('client_message_id IS NOT NULL'))
    op.drop_table('conversation_steps')
    op.drop_index('uq_help_center_tabs_help_center_slug', table_name='help_center_tabs', postgresql_where=sa.text('tab_slug IS NOT NULL'))
    op.drop_index('ix_help_center_tabs_help_center_id', table_name='help_center_tabs')
    op.drop_table('help_center_tabs')
    op.drop_index('ix_conversations_tenant_started', table_name='conversations')
    op.drop_index('ix_conversations_tenant_agent', table_name='conversations')
    op.drop_index('ix_conversations_status', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_agent_tools_agent_id', table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index('ix_tenants_status', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_sync_logs_kb_id', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index('ix_super_admins_status', table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_index('ix_slices_tenant_id', table_name='slices')
    op.drop_index('ix_slices_kb_id', table_name='slices')
    op.drop_index('ix_slices_document_id', table_name='slices')
    op.drop_table('slices')
    op.drop_index('ix_reset_codes_lookup', table_name='password_reset_codes')
    op.drop_index('ix_reset_codes_expires', table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.drop_index('ix_knowledge_bases_tenant_id', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('ix_kb_perm_rules_tenant_kb', table_name='kb_permission_rules')
    op.drop_table('kb_permission_rules')
    op.drop_index('uq_help_centers_public_slug', table_name='help_centers', postgresql_where=sa.text('public_slug IS NOT NULL'))
    op.drop_index('ix_help_centers_tenant_id', table_name='help_centers')
    op.drop_table('help_centers')
    op.drop_index('ix_documents_tenant_id', table_name='documents')
    op.drop_index('ix_documents_kb_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_channels_tenant_id', table_name='channels')
    op.drop_table('channels')
    op.drop_index('ix_api_keys_tenant_id', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_agents_tenant_id', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
